# Phase 1: stay close to defaults. The retained-class rules for kotlinx.serialization come
# from :core:model's consumer-rules.pro. Add app-specific keeps as later phases need them.

# Keep generic signatures for Retrofit + kotlinx.serialization reflection.
-keepattributes Signature
-keepattributes *Annotation*

# Retrofit needs to read method-level annotations.
-keep,allowobfuscation,allowshrinking class kotlin.coroutines.Continuation
-if interface * { @retrofit2.http.* <methods>; }
-keep,allowobfuscation interface <1>

# Google Tink (pulled in transitively by the Stripe Terminal SDK for local encryption) supports
# an optional remote-key-fetching feature this app never calls into. R8 can't otherwise resolve
# those optional classes since none of the actual dependencies (Google API HTTP client, Joda-Time,
# SLF4J's static binder) are on the classpath — this app doesn't need them. Rules generated by AGP
# itself at app/build/outputs/mapping/release/missing_rules.txt; kept here rather than regenerated
# per build.
-dontwarn com.google.api.client.http.GenericUrl
-dontwarn com.google.api.client.http.HttpHeaders
-dontwarn com.google.api.client.http.HttpRequest
-dontwarn com.google.api.client.http.HttpRequestFactory
-dontwarn com.google.api.client.http.HttpResponse
-dontwarn com.google.api.client.http.HttpTransport
-dontwarn com.google.api.client.http.javanet.NetHttpTransport$Builder
-dontwarn com.google.api.client.http.javanet.NetHttpTransport
-dontwarn java.beans.ConstructorProperties
-dontwarn java.beans.Transient
-dontwarn org.joda.time.Instant
-dontwarn org.slf4j.impl.StaticLoggerBinder
-dontwarn org.slf4j.impl.StaticMDCBinder
