package co.monveri.register.model

import java.net.URI
import java.net.URLDecoder

/**
 * Decoded contents of a `monveri://pair?...` QR code generated by the suite admin's
 * Register API Keys page. Mirrors iOS's `PairingPayload` wire format exactly so the same QR
 * pairs either app:
 *
 * ```
 * monveri://pair?v=1
 *                &url=https%3A%2F%2Fapp.monveri.co%2Fstores%2FAB12CD34
 *                &key=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
 *                &name=Carolina%20Thread%20Place
 * ```
 *
 * `storeUrl` is the store base URL up to and including `/stores/<token>` — callers append
 * `api/register/` themselves, same as the manual-entry path.
 */
data class PairingPayload(
    val version: Int,
    val storeUrl: String,
    val apiKey: String,
    val storeName: String?,
    /** Register number (01-99) the server has pinned to this api key, when the QR carries one. */
    val registerNumber: Int? = null,
    /** Friendly label set by the admin on the api key row (e.g. "Counter register"). */
    val keyLabel: String? = null,
) {
    /** `REG02` / `REG07` / etc. — blank when the QR didn't carry a register number. */
    val registerLabel: String
        get() = registerNumber?.let { "REG%02d".format(it) } ?: ""

    /** Falls back to the URL host when the payload didn't include a store name. */
    val displayName: String
        get() = storeName?.trim()?.takeIf { it.isNotEmpty() }
            ?: runCatching { URI(storeUrl).host }.getOrNull()
            ?: storeUrl

    companion object {
        private const val SUPPORTED_VERSION = 1
        private const val SCHEME_PREFIX = "monveri:"

        /**
         * Parses a scanned or pasted string. Returns `null` for any unrecognized shape so a
         * scanner can simply keep the camera live and try the next frame.
         */
        fun parse(rawValue: String): PairingPayload? {
            val trimmed = rawValue.trim()
            if (trimmed.isEmpty()) return null
            if (!trimmed.startsWith(SCHEME_PREFIX, ignoreCase = true)) return null

            // Tolerate both "monveri://pair?..." and "monveri:pair?..." — some encoders omit
            // the double slash.
            var rest = trimmed.substring(SCHEME_PREFIX.length)
            if (rest.startsWith("//")) rest = rest.substring(2)

            val queryIndex = rest.indexOf('?')
            if (queryIndex < 0) return null
            val route = rest.substring(0, queryIndex)
            if (!route.equals("pair", ignoreCase = true)) return null

            val params = rest.substring(queryIndex + 1)
                .split("&")
                .mapNotNull { pair ->
                    val eq = pair.indexOf('=')
                    if (eq < 0) return@mapNotNull null
                    val name = decode(pair.substring(0, eq)).lowercase()
                    val value = decode(pair.substring(eq + 1))
                    if (value.isEmpty()) null else name to value
                }
                .toMap()

            // Version: required. Reject unknown future versions so this app doesn't half-decode
            // a new payload format.
            val version = params["v"]?.toIntOrNull() ?: return null
            if (version != SUPPORTED_VERSION) return null

            val url = params["url"] ?: return null
            if (!url.lowercase().startsWith("http")) return null

            val key = params["key"] ?: return null

            return PairingPayload(
                version = version,
                storeUrl = url,
                apiKey = key,
                storeName = params["name"],
                registerNumber = params["reg"]?.toIntOrNull()?.takeIf { it in 1..99 },
                keyLabel = params["label"]?.trim()?.takeIf { it.isNotEmpty() },
            )
        }

        private fun decode(value: String): String =
            runCatching { URLDecoder.decode(value, "UTF-8") }.getOrDefault(value)
    }
}
